apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: $BITBUCKET_REPO_SLUG
  namespace: $K8S_NAMESPACE
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  data:
  dataFrom:
  - extract:
      key: $K8S_NAMESPACE/$BITBUCKET_REPO_SLUG
