apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: $BITBUCKET_REPO_SLUG
  namespace: $K8S_NAMESPACE
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: cluster-secrets
    kind: ClusterSecretStore
  data:
  dataFrom:
    - extract:
        key: $K8S_NAMESPACE/$BITBUCKET_REPO_SLUG
# ELE NÃO CRIA, ELE SÓ LINKA ATRAVÉS DA LINHA 12, 13 E 14. Então precisa existe previamente.

# SECRETS NÃO PRECISAM DE PERMISSÃO
